### ISSUE TITLE
Key Increase config doesn't work.

### ISSUE THREAD

**Issue by CoolerSynthle** [GlacialSkyfarer/TrialChamberRestock#4]
Hey! I really like your mod, but I don't like the key increase part. I tried to set the config to 0 for the amount to increase by and it still says I need another key even though I set it as 1. I tried fixing it myself but your also don't have 1.0.3's source on the github. Please fix this!

**Comment by iv8512** [comment]
I also set the "costIncrease" to 0 and it is asking for 2 keys when trying open a vault.

**Comment by CoolerSynthle** [comment]
> Just to clarify, is it just asking for a key again, or is it asking for 2?
> 
> (Also, current source code in the repo is 1.0.3, I just didn't upload it as a version)

it's asking for 2 keys

**Comment by RustinPlays** [comment]
Sadly have the same issue. Config set to 0 and wants more and more each time opened. Was there a planned update for that?

**Comment by CodingLegend0100** [comment]
I am also having this issue. The key increase value seems to work for any value except for 0. If the key increase is 0, the mod behaves as if it was still set to 1.

**Comment by GlacialSkyfarer** [comment]
OH SHIT
yeah i guess i just wasn't thinking about the config when i did that line and jhust defaulted to what it should be at 1 lmao

**Comment by GlacialSkyfarer** [comment]
finally got intellij set up again just now, should be an update to fix this and the dependency issues pretty soon
